services:
  - type: web
    name: oauth2-proxy-render
    plan: free
    env: docker
    rootDir: simple/render
    envVars:
      - key: OAUTH2_PROXY_CLIENT_ID
        sync: false
      - key: OAUTH2_PROXY_CLIENT_SECRET
        sync: false
      - key: OAUTH2_PROXY_COOKIE_SECRET
        generateValue: true
      - key: OAUTH2_PROXY_HTTP_ADDRESS
        value: ":10000"
